---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gandi-ddns
data:
  GANDI_DOMAIN: "example.com"
  GANDI_RECORD: "www"
---
apiVersion: v1
kind: Secret
metadata:
  name: gandi-ddns
data:
  GANDI_TOKEN: "My Secret Token"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gandi-ddns
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gandi-ddns
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: cache
            persistentVolumeClaim:
              claimName: gandi-ddns
          containers:
          - name: gandi-ddns
            image: quay.io/ccordoui/container-gandi-ddns:latest
            concurrencyPolicy: Replace
            imagePullPolicy: Always
            restartPolicy: Never
            command:
            - python3
            - gandi-ddns.py
            envFrom:
            - configMapRef:
                name: gandi-ddns
            - secretRef:
                name: gandi-ddns
            volumeMounts:
            - mountPath: "/opt/app-root/src/data"
              name: cache
